language: ruby
rvm:
- 2.6.3
before_install:
- openssl aes-256-cbc -K $encrypted_f2cee5d76fc5_key -iv $encrypted_f2cee5d76fc5_iv
  -in travis_ssh_key.enc -out ~/travis_ssh_key -d
- chmod 600 ~/travis_ssh_key
before_script:
- chmod +x ./script/cibuild
- gem i bundle
- gem i kramdown-syntax-coderay
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 ~/travis_ssh_key
- ssh-add ~/travis_ssh_key
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
  ssh_known_hosts:
  - yanpeipan.cn
cache: bundler
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
after_success:
- ssh -i ~/travis_ssh_key root@yanpeipan.cn "mkdir -p /home/www/yanpeipan.github.com/_site"
  #- scp -i ~/travis_ssh_key -r _site/* root@yanpeipan.cn:/home/www/yanpeipan.github.com/_site/
- rsync -e "ssh -i ~/travis_ssh_key" -r --delete-after --quiet _site/* root@yanpeipan.cn:/home/www/yanpeipan.github.com/_site/
exclude:
- vendor

jobs:
  include:
    - language: node_js
      node_js: stable
      before_script:
          - npm install -g gulp-cli
          - npm install gulp --save-dev
          - npm install gulp-clean-css --save-dev
      script:
      - gulp build
