# main links
main:
  - title: ""
    url: /


spring:
  - title: Spring
  - title: 概述
    url: /spring/00-概述
  - title: Spring核心技术
    url: /spring/01-Spring核心技术
    children:
      - title: "Ioc容器"
        url: /spring/02-Ioc容器
      - title: "验证，数据绑定，类型转换"
        url: /spring/03-Validation, Data Binding, and Type Conversion
      - title: "Spring表达式语言"
        url: /spring/04-Spring Expression Language
      - title: "AOP"
        url: /spring/05-Aspect Oriented Programming with Spring
      - title: "Spring AOP APIs"
        url: /spring/06-Spring AOP APIs
      - title: "Null-safety"
        url: /spring/07-Null-safety
      - title: "Data Buffers and Codecs"
        url: /spring/08-Data Buffers and Codecs
        
spring-security:
  - title: Spring Security
  - title: 特性
    url: /spring-security/00-特性
  - title: 概览
    url: /spring-security/01-概览
  - title: 验证
    url: /spring-security/02-验证
  - title: 授权
    url: /spring-security/03-授权
  - title: 防范漏洞利用
    url: /spring-security/04-防范漏洞利用
  - title: 集成
    url: /spring-security/05-集成
    
        
redis:
  - title: 前言
    url: /redis/00-前言
  - title: 内部数据结构
    children:
        - title: 简单动态字符串
          url: /redis/01-简单动态字符串
        - title: 链表
          url: /redis/02-链表
        - title: 字典
          url: /redis/03-字典
        - title: 跳跃表
          url: /redis/04-跳跃表
        - title: 整数集合
          url: /redis/05-整数集合
        - title: 压缩列表
          url: /redis/06-压缩列表
        - title: 快速列表
          url: /redis/07-快速列表 
        - title: 对象
          url: /redis/08-对象
  - title: 单机数据库
    url: /spring-security/02-单机数据库
