# main links
main:
  - title: ""
    url: /


spring:
  - title: Spring
  - title: 概述
    url: /spring/00-概述
  - title: Spring核心技术
    url: /spring/01-Spring核心技术
    children:
      - title: "Ioc容器"
        url: /spring/01-Ioc容器
      - title: "装配Bean"
        url: /spring/02-装配Bean
      - title: "高级装配"
        url: /spring/03-高级装配
      - title: "面向切面的Spring"
        url: /spring/04-面向切面的Spring
  - title: Web中的Spring
    children:
      - title: "Spring之旅"
        url: /spring/01-Spring之旅

spring-security:
  - title: Spring Security
  - title: 特性
    url: /spring-security/00-特性
  - title: 概览
    url: /spring-security/01-概览
